# Generated by Django 3.2 on 2022-08-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputLang', models.CharField(max_length=20)),
                ('outputLang', models.CharField(max_length=20)),
                ('audioFile', models.FileField(blank=True, upload_to='audio')),
            ],
        ),
    ]
